import Navbar from '@/components/navbar'
import './globals.css'
import { Montserrat, Poppins } from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
})
 
const poppins= Poppins({
  subsets: ['latin'],
  weight: ['400','500', '600' ,'700', '800'],
  variable: '--font-poppins',
  display: 'swap',
})



export const metadata = {
  title: 'Enkapune Cowboy Park',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body suppressHydrationWarning={true}>
        <Navbar />
        {children}</body>
    </html>
  )
}
